export const projects = [
  {
    slug: "ai-translation-platform",
    title: "AI Product Translation Platform",
    description: "AI-powered multilingual product enrichment system",
    image: "/projects/mdm.png",
    tags: ["Azure AI", "Stibo STEP", "MDM", "APIs"],
    details: `Built AI translation workflows integrated with Azure AI services to standardize global product master data. Supports SAP & Excel ingestion and outbound API delivery to analytics platforms.`,
  },
  {
    slug: "global-mdm-integration",
    title: "Global MDM Integration Platform",
    description: "Enterprise MDM ingestion & outbound integration",
    image: "/projects/mdm.png",
    tags: ["SAP", "Excel", "REST APIs", "Data Governance"],
    details: `Designed SAP & Excel ingestion pipelines and outbound REST integrations delivering datasets to SKUVantage (Australia).`,
  },
  {
    slug: "data-quality-framework",
    title: "Enterprise Data Quality Framework",
    description: "Rule-based master data validation platform",
    image: "/projects/mdm.png",
    tags: ["Business Rules", "Validation", "MDM"],
    details: `Implemented centralized business rule engines ensuring data completeness, uniqueness, and consistency.`,
  },
  {
    slug: "product-onboarding-workflows",
    title: "Product Onboarding Automation",
    description: "Workflow-driven global product onboarding",
    image: "/projects/mdm.png",
    tags: ["Workflow Orchestration", "Automation"],
    details: `Designed automated workflows to onboard and approve product data across regions.`,
  },
  {
    slug: "api-outbound-hub",
    title: "Outbound API Integration Hub",
    description: "Secure REST-based outbound delivery platform",
    image: "/projects/mdm.png",
    tags: ["REST APIs", "JSON", "Security"],
    details: `Built centralized outbound API frameworks for analytics and retail platforms.`,
  },
  {
    slug: "sap-excel-ingestion",
    title: "SAP & Excel Ingestion Pipelines",
    description: "Multi-source ingestion platform",
    image: "/projects/mdm.png",
    tags: ["SAP", "Excel", "ETL"],
    details: `Designed automated ingestion pipelines supporting enterprise SAP systems and Excel bulk uploads.`,
  },
  {
    slug: "mdm-governance-model",
    title: "MDM Governance & Stewardship Model",
    description: "Data governance & stewardship platform",
    image: "/projects/mdm.png",
    tags: ["Governance", "Stewardship"],
    details: `Implemented governance workflows ensuring compliance and data ownership accountability.`,
  },
  {
    slug: "analytics-ready-modeling",
    title: "Analytics Ready Data Modeling",
    description: "Dimensional modeling for BI enablement",
    image: "/projects/mdm.png",
    tags: ["Dimensional Modeling", "BI"],
    details: `Designed fact-dimension models to enable BI and analytics workloads.`,
  },
  {
    slug: "sku-optimization-platform",
    title: "SKU Optimization & Rationalization",
    description: "SKU lifecycle and duplication management",
    image: "/projects/mdm.png",
    tags: ["SKU", "Optimization"],
    details: `Built SKU duplication detection and lifecycle management pipelines.`,
  },
  {
    slug: "global-product-syndication",
    title: "Global Product Syndication Platform",
    description: "Cross-market product data syndication",
    image: "/projects/mdm.png",
    tags: ["Syndication", "Retail"],
    details: `Engineered global syndication pipelines delivering standardized datasets to external marketplaces.`,
  },
];
