name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: sohail-shaik-portfolio-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend.zip
